Repository YAPP-Github/Gradmeet-BE, pull requests merged in 2024-12, with the labels that each got.

#1 docs: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 DOCS

#3 feat: 패키지 구조 및 예외처리 관련 로직 설정
  .gitmessage.txt
  src/main/kotlin/com/dobby/backend/domain/exception/DomainErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DomainException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/GenericGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/MemberObject.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/AuditingEntity.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/exception/GeneralException.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/handler/CustomExceptionHandler.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/payload/ApiResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/payload/code/BaseCode.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/payload/code/BaseErrorCode.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/payload/code/ReasonDto.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/payload/code/status/ErrorStatus.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/payload/code/status/SuccessStatus.kt
Labels: ✨ FEATURE

#4 feat: 인증/인가를 위한 JWT 토큰 발급 로직 구현
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/config/ApplicationConfig.kt
  src/main/kotlin/com/dobby/backend/domain/exception/AuthenticationException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DomainErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DomainException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/MemberException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/TokenGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/Member.kt
  src/main/kotlin/com/dobby/backend/domain/model/MemberObject.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/TokenProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/TokenGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProvider.kt
  src/main/kotlin/com/dobby/backend/util/UlidUtils.kt
  src/main/resources/application.yml
  src/main/resources/template-application-local.yml
  src/test/kotlin/com/dobby/backend/config/SpringTestConfig.kt
  src/test/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProviderTest.kt
  src/test/resources/application.yml
Labels: ⚙️ CHORE, ✨ FEATURE

#5 docs: PR 템플릿 양식 개선
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 DOCS, 🔒 HOLD

#7 [YS-49] chore: CI 스크립트 작성 및 PR 오토 템플릿 추가
  .github/workflows/ci-backend.yml
  .github/workflows/pr-auto-template.yml
Labels: ⚙️ CHORE

#8 [YS-35] chore: CD 스크립트 및 도커 파일 추가
  .github/workflows/cd-backend.yml
  build.gradle.kts
  docker-compose.yml
Labels: ⚙️ CHORE

#6 [YS-48] feat: security 관련 설정 추가
  src/main/kotlin/com/dobby/backend/domain/exception/AuthorizationException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DefaultException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/TokenGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProvider.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebExceptionHandler.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/filter/JwtAuthenticationFilter.kt
  src/test/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProviderTest.kt
Labels: ✨ FEATURE

#10 [YS-39] chore: JaCoCo 및 소나클라우드 연동
  .github/workflows/ci-backend.yml
  build.gradle.kts
Labels: ⚙️ CHORE

#12 [YS-41] docs: Swagger 환경설정 적용
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/presentation/api/config/SwaggerConfig.kt
Labels: 📄 DOCS, ⚙️ CHORE

#11 [YS-30] feat: Member 엔티티 설정
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/AuditingEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/Member.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/Participant.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/Researcher.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/common/AuditingEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/GenderType.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/MatchType.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/MemberStatus.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/ProviderType.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/RoleType.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/areaInfo/Area.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/areaInfo/Region.kt
Labels: ✨ FEATURE
