Repository YAPP-Github/Gradmeet-BE, pull requests merged in 2025-02, with the labels that each got.

#76 [YS-178] feat: 연구자/참여자 회원 정보 수정
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateParticipantInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateResearcherInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/model/member/Participant.kt
  src/main/kotlin/com/dobby/backend/domain/model/member/Researcher.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/ParticipantEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/ResearcherGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/UpdateParticipantInfoRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/UpdateResearcherInfoRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateParticipantInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateResearcherInfoUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#77 [YS-201] feat: 추천 실험 공고 메일 전송 로직 구현
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/application/service/EmailService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/GetMatchingExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/VerifyEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/UrlGeneratorGateway.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/SchedulerConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/UrlProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/UrlGeneratorGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/scheduler/SendMatchingEmailJob.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/EmailMapper.kt
  src/test/kotlin/com/dobby/backend/application/service/EmailServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailCodeSendUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailMatchSendUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailVerificationUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/GetMatchingExperimentPostsUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#79 [YS-255] refactor: IdGenerator로 네이밍 변경 및 패키지 이동
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/IdGenerator.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/IdGeneratorGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/identifier/TsidIdGenerator.kt
  src/main/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProvider.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailCodeSendUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
Labels: ♻️ REFACTORING

#80 [YS-256] feat: 회원가입 연락 받을 이메일 중복 비허용 로직 추가
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/VerifyContactEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/MemberGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/MemberEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/ContactEmailVerificationRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/VerifyContactEmailUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#81 [YS-264] feat: 회원 정보 수정 기능을 위한 contactEmail 검증 API 및 로직 추가
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchGoogleUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateParticipantInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateResearcherInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/ValidateContactEmailForSignUpUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/ValidateContactEmailForUpdateUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/MemberGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/OauthLoginResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/MemberResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/AuthMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateParticipantInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateResearcherInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/ValidateContactEmailForSignUpUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/ValidateContactEmailForUpdateUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#82 [YS-202] chore: SpringBoot에 ElastiCache for Redis 설정
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/infrastructure/config/RedisConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/S3Config.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/RedisProperties.kt
  src/main/resources/template-application-local.yml
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
  src/test/resources/application.yml
Labels: ⚙️ CHORE

#88 [YS-282] docs: MIT License 추가
  LICENSE
Labels: 📄 DOCS

#90 [YS-285] refactor: 실험 공고 상세 조회 UseCase가 프레젠테이션 계층을 참조하지 않도록 리팩토링
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCaseTest.kt
Labels: ♻️ REFACTORING

#92 [YS-299] feat: 지역별 공고 개수 조회 UseCase Output 캐싱 적용 및 Redis 테스트 컨테이너 추가
  .github/workflows/ci-dev.yml
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/CacheGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/cache/RedisCacheGatewayImpl.kt
  src/test/kotlin/com/dobby/backend/application/service/ExperimentPostServiceTest.kt
  src/test/kotlin/com/dobby/backend/config/RedisTestContainer.kt
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
  src/test/resources/application-test.yml
Labels: ⚙️ CHORE, ✅ TEST, ✨ FEATURE

#94 [YS-304] refactor: 공고 상세 조회 시, 반환값으로 alarmAgree 필드 추가
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostDetailResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
Labels: ♻️ REFACTORING, 🔥 HOTFIX

#95 [YS-305] fix: 공고 수정 시 날짜 수정 안되는 현상 해결
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
Labels: 🔥 HOTFIX

#96 [YS-306] fix: 공고 수정 시 nullable 필드 및 이미지 생성 버그 수정
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/experiment/UpdateExperimentPostRequest.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#97 [YS-310] feat: 실험 공고 수정 시, 입력 자동완성 지원을 위한 조회 API 구현
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailForUpdateUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailForUpdateUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#98 [YS-311] fix: 성별 무관한 공고에 대해서 남/녀로 필터링했을 때 보이지 않는 현상 해결
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
Labels: 🐛 BUG

#93 [YS-302] refactor: 이메일 전송 최적화
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/application/service/CoroutineDispatcherProvider.kt
  src/main/kotlin/com/dobby/backend/application/service/EmailService.kt
  src/main/kotlin/com/dobby/backend/application/service/TransactionExecutor.kt
  src/main/kotlin/com/dobby/backend/application/usecase/AsyncUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/email/EmailGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/CoroutineConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/coroutine/CoroutineDispatcherProviderImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/coroutine/TransactionCoroutineExecutor.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/email/EmailGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/scheduler/SendMatchingEmailJob.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/EmailController.kt
  src/main/kotlin/com/dobby/backend/util/RetryUtils.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCaseTest.kt
Labels: ♻️ REFACTORING

#99 [YS-314] refactor: ExperimentPost 엔티티의 `univName` 컬럼명을 `place`로 변경
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailForUpdateUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentPostEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/experiment/CreateExperimentPostRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/experiment/UpdateExperimentPostRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostDetailResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/PostInfo.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/service/ExperimentPostServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostApplyMethodUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailForUpdateUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostsUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetMyExperimentPostsUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostRecruitStatusUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/GetMatchingExperimentPostsUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCaseTest.kt
Labels: ♻️ REFACTORING

#100 [YS-312] refactor: 공고 수정 관련 요구사항 반영
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ApplyMethod.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/TargetGroup.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/experiment/UpdateExperimentPostRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/service/ExperimentPostServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCaseTest.kt
Labels: 🐛 BUG, ♻️ REFACTORING, ✅ TEST

#101 [YS-328] feat: 이용 약관 관련 기능 추가
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetParticipantInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetResearcherInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateParticipantInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateResearcherInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/MemberConsentGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/member/MemberConsent.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/MemberConsentEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberConsentRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberConsentGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/ParticipantSignupRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/ResearcherSignupRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/UpdateParticipantInfoRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/UpdateResearcherInfoRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/ParticipantInfoResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/ResearcherInfoResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/GetParticipantInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/GetResearcherInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateParticipantInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateResearcherInfoUseCaseTest.kt
Labels: 🐛 BUG, ✅ TEST, ✨ FEATURE

#103 [YS-332] refactor: 회원가입(SignUp) 관련 메서드 네이밍 통일
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/GetMemberByIdUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/SignUpResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
Labels: ♻️ REFACTORING

#102 [YS-331] refactor: 인증 코드 캐싱 적용 및 처리율 제한 로직 추가
  src/main/kotlin/com/dobby/backend/application/usecase/member/VerifyResearcherEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/VerifyEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/CacheGateway.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/email/VerificationGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/Verification.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/VerificationEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/VerificationRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/cache/RedisCacheGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/email/VerificationGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/util/RetryUtils.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/VerifyResearcherEmailUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailVerificationUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/VerifyEmailUseCaseTest.kt
Labels: 🐛 BUG, ♻️ REFACTORING, ✅ TEST

#104 [YS-333] fix: AuthorizationDeniedException을 403 Forbidden으로 정상 처리하도록 수정
  src/main/kotlin/com/dobby/backend/presentation/api/config/exception/WebExceptionHandler.kt
Labels: 🐛 BUG

#107 [YS-340] fix: 매칭 공고 이메일 전송 시 대상이 올바르게 필터링되지 않는 현상 해결
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#108 [YS-342] hotfix: 회원 정보 수정 시 기존 실험 게시글이 삭제되지 않도록 cascade 설정 변경
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/MemberEntity.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#106 [YS-329] feat: Redis Lettuce 기반 분산락 도입 및 AOP 적용
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/application/aop/AopForNewTransaction.kt
  src/main/kotlin/com/dobby/backend/application/aop/DistributedLock.kt
  src/main/kotlin/com/dobby/backend/application/aop/DistributedLockAspect.kt
  src/main/kotlin/com/dobby/backend/application/common/LockKeyProvider.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/infrastructure/lock/RedisLockManager.kt
  src/test/kotlin/com/dobby/backend/application/service/ExperimentPostServiceTest.kt
  src/test/kotlin/com/dobby/backend/concurrency/GetExperimentPostDetailUseCaseConcurrencyTest.kt
Labels: ✅ TEST, ✨ FEATURE

#110 [YS-66] feat: CloudWatch 로그 전송 및 환경별 로그 그룹 분리 적용
  build.gradle.kts
  src/main/resources/logback-spring.xml
Labels: ⚙️ CHORE, ✨ FEATURE

#111 [YS-344] hotfix: S3 SDK v1 → v2 버전 업그레이드
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/TargetGroupGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/S3Config.kt
  src/main/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProvider.kt
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
Labels: 🐛 BUG, ⚙️ CHORE, 🔥 HOTFIX

#109 [YS-283] refactor: 이메일 템플릿 적용
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/application/common/CoroutineDispatcherProvider.kt
  src/main/kotlin/com/dobby/backend/application/common/TransactionExecutor.kt
  src/main/kotlin/com/dobby/backend/application/service/EmailService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/EmailTemplateLoader.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/email/EmailGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/TemplateProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/coroutine/CoroutineDispatcherProviderImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/coroutine/TransactionCoroutineExecutor.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enums/experiment/TimeSlot.kt
  src/main/kotlin/com/dobby/backend/infrastructure/email/ThymeleafEmailTemplateLoader.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/email/EmailGatewayImpl.kt
  src/main/resources/templates/code-template.html
  src/main/resources/templates/matching-template.html
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCaseTest.kt
Labels: ♻️ REFACTORING

#112 [YS-345] feat: 데모데이를 위한 회원 매칭 이메일 동의 여부 조작 API 구현
  src/main/kotlin/com/dobby/backend/application/service/SchedulerService.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/MemberConsentGateway.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/MemberGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/MemberConsentEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberConsentGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/SchedulerController.kt
Labels: ✨ FEATURE

#114 [YS-347] refactor: GetExperimentPostDetailUseCase에서 적용된 분산락 기능 제거
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/test/kotlin/com/dobby/backend/concurrency/GetExperimentPostDetailUseCaseConcurrencyTest.kt
Labels: ♻️ REFACTORING

#115 [RELEASE] 릴리즈 v1.1.1
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
Labels: 🚀 RELEASE, 🔥 HOTFIX

#116 [YS-64] chore: Flyway 도입 및 초기 마이그레이션 스크립트 추가
  build.gradle.kts
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/template-application-local.yml
  src/test/resources/application-test.yml
Labels: ⚙️ CHORE

#117 [YS-356] feat: AOP 기반 요청/응답 로깅 적용 및 민감 정보 마스킹 추가
  src/main/kotlin/com/dobby/backend/infrastructure/logging/LoggingAspect.kt
  src/main/kotlin/com/dobby/backend/infrastructure/logging/SensitiveDataMasker.kt
  src/main/resources/logback-spring.xml
Labels: ⚙️ CHORE, ✨ FEATURE

#119 [YS-352] refactor: 학교 메일 인증을 완료했으나 회원가입을 마치지 않은 사용자를 구분하는 로직 추가
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/ResearcherGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ResearcherRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/ResearcherGatewayImpl.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCaseTest.kt
Labels: ♻️ REFACTORING, ✅ TEST

#120 [YS-360] fix: 모집완료된 공고에 대해서는 매칭 공고 알림이 안 가도록 처리
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
Labels: 🐛 BUG

#121 [YS-330] refactor: 이메일 전송 기능 AWS SES로 마이그레이션
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/infrastructure/config/SESClientConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/EmailProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/SESProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/email/EmailGatewayImpl.kt
  src/test/resources/application-test.yml
Labels: ♻️ REFACTORING

#122 [YS-371] refactor: 불필요한 코루틴 제거
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/application/common/CoroutineDispatcherProvider.kt
  src/main/kotlin/com/dobby/backend/application/common/TransactionExecutor.kt
  src/main/kotlin/com/dobby/backend/application/service/EmailService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/AsyncUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/SendMatchingEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/email/EmailGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/CoroutineConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/coroutine/CoroutineDispatcherProviderImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/coroutine/TransactionCoroutineExecutor.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/email/EmailGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/scheduler/SendMatchingEmailJob.kt
  src/main/kotlin/com/dobby/backend/util/RetryUtils.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/SendEmailCodeUseCaseTest.kt
Labels: ♻️ REFACTORING

#123 [YS-372] refactor: 사용되지 않는 분산락 관련 코드 정리
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/application/aop/AopForNewTransaction.kt
  src/main/kotlin/com/dobby/backend/application/aop/DistributedLock.kt
  src/main/kotlin/com/dobby/backend/application/aop/DistributedLockAspect.kt
  src/main/kotlin/com/dobby/backend/application/common/LockKeyProvider.kt
Labels: ♻️ REFACTORING
