Repository YAPP-Github/Gradmeet-BE, pull requests merged in 2025-03, with the labels that each got.

#129 [YS-382] test: 멀티모듈 전환 중 누락된 infrastructure 테스트 코드 추가
  infrastructure/build.gradle.kts
  infrastructure/src/test/kotlin/com/dobby/DobbyBackendApplicationTests.kt
  infrastructure/src/test/kotlin/com/dobby/config/SpringTestConfig.kt
  infrastructure/src/test/kotlin/com/dobby/external/s3/S3PreSignedUrlProviderTest.kt
  infrastructure/src/test/kotlin/com/dobby/security/token/JwtTokenProviderTest.kt
  infrastructure/src/test/resources/application-test.yml
Labels: ⚙️ CHORE, ✅ TEST

#130 [YS-385] docs: README 업데이트
  README.md
Labels: 📄 DOCS

#133 [YS-392] fix: 이메일 인증 코드 전송 API 에러 해결
  infrastructure/build.gradle.kts
Labels: 🐛 BUG

#132 [YS-391] chore: 루트 프로젝트 build.gradle 정리 및 Ktlint 적용
  .editorconfig
  application/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  domain/build.gradle.kts
  infrastructure/build.gradle.kts
  presentation/build.gradle.kts
  settings.gradle.kts
Labels: ⚙️ CHORE, ♻️ REFACTORING

#135 [YS-401] chore: GitHub Actions 워크플로우에 ktlint 코드 품질 검사 추가
  .github/workflows/ci-dev.yml
  .github/workflows/ktlint-check.yml
Labels: ⚙️ CHORE
