Repository YAPP-Github/Gradmeet-BE, pull requests merged in 2025-01, with the labels that each got.

#14 [YS-37] chore: S3 연동 및 Pre-SignedUrl 로직 구현
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/config/ApplicationConfig.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/S3Gateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/S3Config.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/S3Properties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/TokenProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/S3GatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProvider.kt
  src/main/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProvider.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/PreSignedUrlResponse.kt
  src/main/resources/application.yml
  src/main/resources/template-application-local.yml
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
  src/test/resources/application.yml
Labels: ⚙️ CHORE, ✨ FEATURE

#13 [YS-31] feat: 구글 OAuth 로그인 구현
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/application/mapper/OauthUserMapper.kt
  src/main/kotlin/com/dobby/backend/application/service/OauthService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/AuthenticationException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/MemberException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/OauthException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/SignInRoleMismatchException.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/properties/GoogleAuthProperties.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/Member.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/Participant.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/Researcher.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ParticipantRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/feign/GoogleAuthFeignClient.kt
  src/main/kotlin/com/dobby/backend/infrastructure/feign/GoogleUserInfoFeginClient.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/SwaggerConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/GoogleTokenRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/OauthLoginRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/OauthUserDto.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/GoogleInfoResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/GoogleTokenResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/OauthLoginResponse.kt
  src/main/kotlin/com/dobby/backend/util/AuthenticationUtils.kt
  src/main/resources/application.yml
  src/test/kotlin/com/dobby/backend/DobbyBackendApplicationTests.kt
  src/test/kotlin/com/dobby/backend/application/mapper/OauthUserMapperTest.kt
  src/test/kotlin/com/dobby/backend/application/service/OauthServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoTest.kt
  src/test/kotlin/com/dobby/backend/infrastructure/database/entity/TestEntity.kt
  src/test/kotlin/com/dobby/backend/infrastructure/database/entity/common/AuditingEntityTest.kt
  src/test/kotlin/com/dobby/backend/infrastructure/repository/TestEntityRepository.kt
  src/test/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProviderTest.kt
  src/test/resources/application.yml
Labels: ⚙️ CHORE, ✨ FEATURE

#16 [YS-65] feat: 테스트용 토큰 강제 발급 API & AccessToken 갱신 API 구현
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/DobbyBackendApplication.kt
  src/main/kotlin/com/dobby/backend/application/mapper/OauthUserMapper.kt
  src/main/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/GenerateTestToken.kt
  src/main/kotlin/com/dobby/backend/application/usecase/GenerateTokenWithRefreshToken.kt
  src/main/kotlin/com/dobby/backend/application/usecase/GetMemberById.kt
  src/main/kotlin/com/dobby/backend/application/usecase/UseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/MemberGateway.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/TokenGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/Member.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/MemberEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/ParticipantEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/ResearcherEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/common/AuditingEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/ProviderType.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enum/RoleType.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberJpaRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ParticipantRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/MemberGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/TokenGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/MemberRefreshTokenRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/MemberResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/MemberSignInResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/OauthLoginResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/TestMemberSignInResponse.kt
  src/main/kotlin/com/dobby/backend/util/AuthenticationUtils.kt
  src/test/kotlin/com/dobby/backend/DobbyBackendApplicationTests.kt
  src/test/kotlin/com/dobby/backend/application/mapper/OauthUserMapperTest.kt
  src/test/kotlin/com/dobby/backend/application/service/OauthServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoTest.kt
  src/test/kotlin/com/dobby/backend/domain/usecase/GenerateTestTokenTest.kt
  src/test/kotlin/com/dobby/backend/domain/usecase/GenerateTokenWithRefreshTokenTest.kt
  src/test/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProviderTest.kt
Labels: ✨ FEATURE

#17 [YS-67] feat: 실험자 회원가입 API 구현
  src/main/kotlin/com/dobby/backend/application/mapper/OauthUserMapper.kt
  src/main/kotlin/com/dobby/backend/application/mapper/SignupMapper.kt
  src/main/kotlin/com/dobby/backend/application/service/OauthService.kt
  src/main/kotlin/com/dobby/backend/application/service/SignupService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/ParticipantSignupUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/MemberException.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/ParticipantEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/ResearcherEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/feign/GoogleAuthFeignClient.kt
  src/main/kotlin/com/dobby/backend/infrastructure/feign/GoogleUserInfoFeginClient.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/SignupController/ParticipantSignupController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/ParticipantSignupRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/MemberSignInResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/OauthLoginResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/google/GoogleInfoResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/google/GoogleTokenResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/signup/ParticipantSignupResponse.kt
  src/test/kotlin/com/dobby/backend/application/mapper/SignupMapperTest.kt
  src/test/kotlin/com/dobby/backend/application/service/OauthServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/ParticipantSignupUseCaseTest.kt
Labels: ✨ FEATURE

#25 [YS-131] refact: WebSecurityConfig 우선순위 수정 및 memberId 삽입 위치 변경
  src/main/kotlin/com/dobby/backend/application/mapper/SignupMapper.kt
  src/main/kotlin/com/dobby/backend/application/mapper/VerificationMapper.kt
  src/main/kotlin/com/dobby/backend/application/service/AuthService.kt
  src/main/kotlin/com/dobby/backend/application/service/EmailService.kt
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/service/PostService.kt
  src/main/kotlin/com/dobby/backend/application/service/SignupService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/GenerateTestTokenUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/GenerateTokenWithRefreshTokenUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetResearcherInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/VerifyResearcherEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/EmailCodeSendUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/EmailVerificationUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/EmailController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/SignupController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/expirement/CreateExperimentPostRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/MemberSignInResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/OauthLoginResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/expirement/CreateExperimentResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/EmailSendResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/EmailVerificationResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/MemberResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/SignupResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/EmailMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/SignupMapper.kt
  src/main/kotlin/com/dobby/backend/util/AuthenticationUtils.kt
  src/test/kotlin/com/dobby/backend/application/service/EmailServiceTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/GenerateTestTokenUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/GenerateTokenWithRefreshTokenUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/util/AuthenticationUtilsTest.kt
Labels: ♻️ REFACTORING

#26 [YS-132] chore: QueryDSL 설정 추가
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/infrastructure/database/QueryDslConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/VerificationEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/common/AuditingEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentImageEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentPostEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/MemberEntity.kt
Labels: ⚙️ CHORE

#28 [YS-117] feat: 특정 실험 공고 참여 방법 조회 API 구현
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostApplyMethodUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/expirement/ExperimentPostApplyMethodResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/expirement/ExperimentPostDetailResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostApplyMethodUseCaseTest.kt
  src/test/resources/application.yml
Labels: ✨ FEATURE

#30 [YS-145] hotfix: 실험 공고 조회 관련 API에 대해 인증 생략
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#33 [YS-143] feat: 실험 공고 이미지 등록을 위한 S3 Pre-Signed Url 발급 API 구현
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GenerateExperimentPostPreSignedUrlUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/S3Gateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/S3GatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProvider.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/PreSignedUrlRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/PreSignedUrlResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GenerateExperimentPostPreSignedUrlUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
Labels: ✅ TEST, ✨ FEATURE

#36 [YS-159] feat: 추가 지역에 대해 선택하지 않은 참여자 지역 정보에 NONE 값 적용
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostCountsByRegionUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/model/member/Participant.kt
  src/main/kotlin/com/dobby/backend/infrastructure/converter/ParticipantConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enums/areaInfo/Area.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enums/areaInfo/Region.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/ParticipantEntity.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
Labels: 🐛 BUG, ✨ FEATURE, 🔥 HOTFIX

#38 [YS-160] refact: 연구자 회원가입 요청에서 사용하지 않는 이메일 인증 필드 삭제
  src/main/kotlin/com/dobby/backend/application/mapper/VerificationMapper.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/EmailController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/EmailSendRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/EmailVerificationRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/ParticipantSignupRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/ResearcherSignupRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/EmailMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
Labels: ♻️ REFACTORING

#34 [YS-141] feat: 실험자 본인이 작성한 공고 게시글 조회 API 구현
  src/main/kotlin/com/dobby/backend/application/mapper/MemberMapper.kt
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/service/PaginationService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetMyExperimentPostTotalCountUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetMyExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/PaginatedResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/PostInfo.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/MyExperimentPostResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/GetMyExperimentPostTotalCountUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/GetMyExperimentPostsUseCaseTest.kt
Labels: ✨ FEATURE

#35 [YS-130] feat: 기간이 지난 공고 state 변경 스케줄링 구현
  build.gradle.kts
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExpiredExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/config/SchedulerConfig.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/scheduler/ExpiredExperimentPostJob.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCaseTest.kt
Labels: ✨ FEATURE

#40 [YS-161] 공고 전체 목록 조회 모집 상태 오타 수정
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostsResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#41 [YS-170] refact: 실험 공고 상세 정보 조회 응답에 `isAuthor` 추가 및 JwtOptionalAuthenticationFilter 추가
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/filter/JwtOptionalAuthenticationFilter.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostDetailResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/main/kotlin/com/dobby/backend/util/AuthenticationUtils.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCaseTest.kt
Labels: ⚙️ CHORE, ♻️ REFACTORING

#42 [YS-173] refact: ExperimentPost의 `recruitDone` 컬럼명 변경 및 공고 전체 조회 API, 지역별 공고 개수 조회 API 로직 리팩터링
  src/main/kotlin/com/dobby/backend/application/mapper/ExperimentMapper.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostCountsByAreaUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostCountsByRegionUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetMyExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/CustomFilter.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enums/experiment/RecruitStatus.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentPostEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/experiment/CustomFilter.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostDetailResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostsResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/MyExperimentPostResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/mapper/ExperimentMapperTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostApplyMethodUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostCountsByAreaUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostCountsByRegionUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostsUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/GetMyExperimentPostsUseCaseTest.kt
Labels: ♻️ REFACTORING

#46 [YS-182] config: 사용하지 않는 Naver OAuth scope 제거
  src/main/resources/application.yml
Labels: ⚙️ CHORE

#47 [YS-185] hotfix: NaverOAuth 응답 구조 수정
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/infrastructure/feign/naver/NaverUserInfoFeignClient.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/naver/NaverInfoResponse.kt
  src/main/resources/template-application-local.yml
  src/test/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCaseTest.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#43 [YS-174] refact: 코드 커버리지 측정을 위해 추가했던 Jacoco 및 Sonarcloud 설정 제거
  .github/workflows/ci-backend.yml
  build.gradle.kts
Labels: ⚙️ CHORE, 🔒 HOLD

#44 [YS-177] refact: 실험 공고 전체 조회 API 응답에 페이지네이션 관련 필드 포함하도록 리팩터링
  src/main/kotlin/com/dobby/backend/application/mapper/ExperimentMapper.kt
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostTotalCountByCustomFilterUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostCustomRepositoryImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/experiment/ExperimentPostResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostTotalCountByCustomFilterUseCaseTest.kt
Labels: ♻️ REFACTORING, ✅ TEST

#45 [YS-142] feat: 실험자가 작성한 자신의 실험 공고 게시글 모집 상태 변경 API 구현
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/UpdateMyExperimentPostRecruitStatusUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ExperimentPostException.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/infrastructure/converter/ExperimentPostConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentPostEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/repository/ExperimentPostRepository.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/UpdateMyExperimentPostRecruitStatusUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#49 [YS-186] refact: NaverOAuth email 관련 필드 not-null로 변경 및 자잘한 리팩터링
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/GenerateTestTokenUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/auth/NaverAuthGateway.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/member/MemberGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/auth/NaverAuthGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebExceptionHandler.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/auth/naver/NaverTokenResponse.kt
  src/test/kotlin/com/dobby/backend/application/usecase/auth/GenerateTestTokenUseCaseTest.kt
Labels: ♻️ REFACTORING

#50 [YS-187] refact: Auth 관련 응답 매핑 로직을 Mapper 클래스로 분리
  src/main/kotlin/com/dobby/backend/application/service/AuthService.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/AuthMapper.kt
Labels: ♻️ REFACTORING

#48 [YS-180] refact: 실험 공고 작성 로직 중, imageList 처리 리팩터링
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ExperimentPostException.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentImage.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/infrastructure/converter/ExperimentPostConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentImageEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/experiment/ExperimentPostEntity.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/experiment/CreateExperimentPostRequest.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
Labels: 🐛 BUG, ♻️ REFACTORING, 🔒 HOLD

#52 [YS-178] feat: 실험자가 작성한 공고 게시글 삭제 API 구현
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/DeleteExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/member/DefaultResponse.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/DeleteExperimentPostUseCaseTest.kt
Labels: ✅ TEST, ✨ FEATURE

#53 [YS-197] refact: 실험자 마이페이지 실험 공고 관련 API URI 변경
  src/main/kotlin/com/dobby/backend/application/mapper/MemberMapper.kt
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetMyExperimentPostTotalCountUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetMyExperimentPostsUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostRecruitStatusUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/ExperimentPostController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/MemberController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/ExperimentPostMapper.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/MemberMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostsUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetMyExperimentPostTotalCountUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetMyExperimentPostsUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostRecruitStatusUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCaseTest.kt
Labels: ♻️ REFACTORING

#57 [YS-209] hotfix: 실험 공고 참여 방법 조회 API 호출 시, 인증 생략하도록 수정
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#58 [YS-210] hotfix: 참여자 회원가입 API matchType nullable로 변경
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/request/member/ParticipantSignupRequest.kt
Labels: 🐛 BUG, 🔥 HOTFIX

#59 [YS-184] chore: 운영 환경에서의 배포를 위한 cicd 파일 추가
  .github/workflows/cd-dev.yml
  .github/workflows/cicd-prod.yml
  docker-compose-prod.yml
  scripts/deploy.sh
Labels: ⚙️ CHORE, 🚀 RELEASE

#63 [YS-229] refact: 배포를 위해 제거했던 디스코드 알림 조건문 복구
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebExceptionHandler.kt
Labels: ♻️ REFACTORING

#64 [YS-230] hotfix: CORS 설정 변경
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/properties/AllowedOriginsProperties.kt
  src/main/resources/application.yml
  src/main/resources/template-application-local.yml
Labels: ⚙️ CHORE, 🔥 HOTFIX

#65 [YS-191] refact: 회원가입 로직 리팩터링
  src/main/kotlin/com/dobby/backend/application/mapper/SignupMapper.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/model/member/Member.kt
  src/main/kotlin/com/dobby/backend/domain/model/member/Participant.kt
  src/main/kotlin/com/dobby/backend/infrastructure/converter/MemberConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/converter/ParticipantConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/converter/ResearcherConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/member/ResearcherEntity.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/MemberGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/ParticipantGatewayImpl.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/member/ResearcherGatewayImpl.kt
Labels: ♻️ REFACTORING

#68 [YS-223] fix: 서로 다른 Role에 대해 로그인 시도 시 에러 처리
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchGoogleUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/SignInRoleMismatchException.kt
  src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
  src/main/kotlin/com/dobby/backend/presentation/api/mapper/AuthMapper.kt
  src/test/kotlin/com/dobby/backend/application/usecase/auth/FetchGoogleUserInfoUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCaseTest.kt
Labels: 🐛 BUG, ♻️ REFACTORING

#69 [YS-193] refact: 기존 ENUM 기반 예외 핸들링을 sealed class로 리팩터링
  src/main/kotlin/com/dobby/backend/application/service/ExperimentPostService.kt
  src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchGoogleUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/FetchNaverUserInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/auth/GenerateTestTokenUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/DeleteExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostApplyMethodUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostRecruitStatusUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetParticipantInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/GetResearcherInfoUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/VerifyResearcherEmailUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/EmailCodeSendUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/member/email/EmailVerificationUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/exception/AuthenticationException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/AuthorizationException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DefaultException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DobbyException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/DomainException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ErrorCode.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ExperimentPostException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/MemberException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/OauthException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ParticipantException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/ResearcherException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/SignInRoleMismatchException.kt
  src/main/kotlin/com/dobby/backend/domain/exception/VerificationException.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enums/areaInfo/Region.kt
  src/main/kotlin/com/dobby/backend/infrastructure/database/entity/enums/experiment/RecruitStatus.kt
  src/main/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProvider.kt
  src/main/kotlin/com/dobby/backend/infrastructure/token/JwtTokenProvider.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebExceptionHandler.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/exception/DobbyExceptionHandler.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/exception/ExceptionResponseFactory.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/exception/WebExceptionHandler.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/com/dobby/backend/presentation/api/config/filter/JwtOptionalAuthenticationFilter.kt
  src/main/kotlin/com/dobby/backend/presentation/api/dto/response/ExceptionResponse.kt
  src/main/kotlin/com/dobby/backend/util/EmailUtils.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostCountsByAreaUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/GetExperimentPostDetailUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/infrastructure/s3/S3PreSignedUrlProviderTest.kt
Labels: ♻️ REFACTORING, 🔒 HOLD

#70 [YS-231] test: 누락된 유즈케이스 테스트 코드 작성
  src/main/kotlin/com/dobby/backend/infrastructure/converter/ExperimentPostConverter.kt
  src/main/kotlin/com/dobby/backend/infrastructure/gateway/experiment/ExperimentPostGatewayImpl.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/CreateParticipantUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/CreateResearcherUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/VerifyResearcherEmailUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailCodeSendUseCaseTest.kt
  src/test/kotlin/com/dobby/backend/application/usecase/member/email/EmailVerificationUseCaseTest.kt
Labels: ✅ TEST

#71 [YS-235] refact: 공고 등록/공고 수정 로직 리팩터링
  src/main/kotlin/com/dobby/backend/application/mapper/ExperimentMapper.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/application/usecase/experiment/UpdateExperimentPostUseCase.kt
  src/main/kotlin/com/dobby/backend/domain/gateway/experiment/ExperimentPostGateway.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ApplyMethod.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentImage.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/ExperimentPost.kt
  src/main/kotlin/com/dobby/backend/domain/model/experiment/TargetGroup.kt
  src/test/kotlin/com/dobby/backend/application/usecase/experiment/CreateExperimentPostUseCaseTest.kt
Labels: ♻️ REFACTORING, ✅ TEST

#72 [YS-236] chore: 개발/운영 환경에 따라 도커 이미지에 태그 추가하도록 수정
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: ⚙️ CHORE
